# Generated by Django 5.0.7 on 2024-08-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0005_alter_censorinfo_certified_alter_censorinfo_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
