# Generated by Django 5.0.7 on 2024-08-25 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0006_alter_movieinfo_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='directed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direc', to='hello_app.director'),
        ),
    ]
