# Generated by Django 5.0.7 on 2024-08-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0002_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
