# Generated by Django 5.0.7 on 2024-08-10 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0003_movieinfo_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='censorinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField()),
                ('certified', models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='img',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='censor_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie', to='hello_app.censorinfo'),
        ),
    ]
