# Generated by Django 5.0.7 on 2024-08-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0004_censorinfo_alter_movieinfo_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censorinfo',
            name='certified',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='censorinfo',
            name='rating',
            field=models.CharField(null=True),
        ),
    ]
